---
data_source: temperature_readings # SQL table
title: Temperature of vials
mqtt_topic: temperature_control/temperature
key: temperature
source: app
payload_key: temperature
y_axis_label: temperature, ℃
interpolation: stepAfter
y_axis_domain: [22.5, 37.5]
lookback: 100000
fixed_decimals: 1
delta_hours: 1
