name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python libraries
        run: |
          pip install -e .
          pip install -r requirements.txt
          pip install pyyaml

          wget https://github.com/Gadgetoid/PY_LGPIO/releases/download/0.2.2.0/lgpio-0.2.2.0.tar.gz -O lgpio-0.2.2.0.tar.gz
          tar -xvzf lgpio-0.2.2.0.tar.gz
          cd lgpio-0.2.2.0
          python setup.py develop

          pip list

      - name: Mosquitto MQTT Broker in GitHub Actions
        uses: Namoshek/mosquitto-github-action@v1
        with:
          version: '1.6'

      - name: Create dot_pioreactor folder
        run: |
           mkdir -p .pioreactor/storage

      - name: Run tests
        run:  |
          pytest tests/ -vv --timeout 600 --random-order --durations 15
        env:
          TESTING: 1
          TMPDIR: /tmp/
